fileVersion: 1
id: "3"
mappingDefinitions:
  CUSTOMER:
    database: ""
    schema: ""
  DEMO:
    database: DEMO
    schema: PROD
  POS:
    database: ""
    schema: ""
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
name: Production
type: Environment
